### ISSUE TITLE
[BUG] NullReferenceException when regedit key missing for darkmode

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#148]
Was reported 2x via mail

1:
System.NullReferenceException: Object reference not set to an instance of an object.   at SystemTrayMenu.Config.IsDarkModeActive() in D:\a\1\s\Config\Config.cs:line 131   at SystemTrayMenu.Config.IsDarkMode() in D:\a\1\s\Config\Config.cs:line 111   at SystemTrayMenu.UserInterface.Menu..ctor() in D:\a\1\s\UserInterface\Menu.cs:line 86   at SystemTrayMenu.Business.Menus.Create(MenuData menuData, String title) in D:\a\1\s\Business\Menus.cs:line 595   at SystemTrayMenu.Business.Menus.MainPreload() in D:\a\1\s\Business\Menus.cs:line 510   at SystemTrayMenu.App..ctor() in D:\a\1\s\Business\App.cs:line 36   at SystemTrayMenu.Program.Main() in D:\a\1\s\Business\Program.cs:line 38

2.
System.NullReferenceException: Object reference not set to an instance of an object. at SystemTrayMenu.Config.IsDarkModeActive() in D:\a\1\s\Config\Config.cs:line 131 at SystemTrayMenu.Config.IsDarkMode() in D:\a\1\s\Config\Config.cs:line 111 at SystemTrayMenu.UserInterface.Menu..ctor() in D:\a\1\s\UserInterface\Menu.cs:line 86 at SystemTrayMenu.Business.Menus.Create(MenuData menuData, String title) in D:\a\1\s\Business\Menus.cs:line 595 at SystemTrayMenu.Business.Menus.MainPreload() in D:\a\1\s\Business\Menus.cs:line 510 at SystemTrayMenu.App..ctor() in D:\a\1\s\Business\App.cs:line 36 at SystemTrayMenu.Program.Main() in D:\a\1\s\Business\Program.cs:line 38

**Comment by Hofknecht** [comment]
![image](https://user-images.githubusercontent.com/52528841/114597821-80cc5d80-9c91-11eb-8a7b-6890c9a018da.png)
