### ISSUE TITLE
[BUG] ObjectDisposedException at NativeWindow.Callback

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#172]
Thank you Dietrich H. for reporting this bug

System.ObjectDisposedException: Cannot access a disposed object.Object name: 'DataGridView'. at System.Windows.Forms.Control.CreateHandle() at System.Windows.Forms.Control.get_Handle() at System.Windows.Forms.Control.PointToClient(Point p) at System.Windows.Forms.DataGridView.UpdateMouseEnteredCell(HitTestInfo hti, MouseEventArgs e) at System.Windows.Forms.DataGridView.OnMouseMove(MouseEventArgs e) at System.Windows.Forms.Control.WmMouseMove(Message

**Comment by Hofknecht** [comment]
Thank you Dietrich H. for answer and logfile.

Dietrich H.:
The bug occurs every time SystemTrayMenu is called. If you close the error message, the menu usually appears.

![image](https://user-images.githubusercontent.com/52528841/119222493-ec0d1900-baf4-11eb-9e84-6849a05bd0e9.png)

ERROR Application Crashed
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'DataGridView'.
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.PointToClient(Point p)
   at System.Windows.Forms.DataGridView.UpdateMouseEnteredCell(HitTestInfo hti, MouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
INFO Restart by 'ByThreadException'



Addionally in logfile
ERROR Application Crashed
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
   at SystemTrayMenu.Handler.WaitToLoadMenu.SetData(DataGridView dgv, Int32 rowIndex) in D:\a\1\s\Business\WaitToLoadMenu.cs:line 195
   at SystemTrayMenu.Handler.WaitToLoadMenu.MouseEnter(Object sender, DataGridViewCellEventArgs e) in D:\a\1\s\Business\WaitToLoadMenu.cs:line 62
   at SystemTrayMenu.Helper.DgvMouseRow.TriggerRowMouseEnter(DataGridView dgv, DataGridViewCellEventArgs e) in D:\a\1\s\Helpers\DgvMouseRow.cs:line 97
   at SystemTrayMenu.Helper.DgvMouseRow.CellMouseEnter(Object sender, DataGridViewCellEventArgs newEventArgs) in D:\a\1\s\Helpers\DgvMouseRow.cs:line 49
   at System.Windows.Forms.DataGridView.OnCellMouseEnter(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.UpdateMouseEnteredCell(HitTestInfo hti, MouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
2021.05.16 09:17:50.203 1  INFO Restart by 'ByThreadException'

**Comment by Hofknecht** [comment]
i can now reproduce

![image](https://user-images.githubusercontent.com/52528841/120061728-d18bf000-c05e-11eb-880b-68ba07784540.png)

![image](https://user-images.githubusercontent.com/52528841/120061731-d6e93a80-c05e-11eb-986b-8667d24d7645.png)

![image](https://user-images.githubusercontent.com/52528841/120061735-db155800-c05e-11eb-90dd-b3be80af97da.png)

![image](https://user-images.githubusercontent.com/52528841/120061739-e10b3900-c05e-11eb-9a41-6b5bf1aedf3e.png)

as you can see in screenshots, #173 is follow up bug, so it is directly related

you can not see the root cause here, but now it is clear it was Revision: a005582 [Feature] Show link overlay for files like lnk & URL (#166), version 1.0.17.26

there is changed disposing of not cached icons, but the problem is the icon for standard browser, which was not chached and then disposed, but the method itselfs retrurns same instance, so when one menu diposes, it get's diposed for others too leading to the internal nativ call error

Solution is to also cache icon for standardbrowser, which makes the stm also faster (<1ms each icon for call (URL) instead 3-5ms)
