### ISSUE TITLE
[BUG] ArgumentOutOfRangeException at NativeWindow.Callback

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#173]
Thank you Ralf K. and Peter S. for reporting this bug

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'e.ColumnIndex')   at System.Windows.Forms.DataGridView.OnCellMouseMove(DataGridViewCellMouseEventArgs e)   at System.Windows.Forms.DataGridView.UpdateMouseEnteredCell(HitTestInfo hti, MouseEventArgs e)   at System.Windows.Forms.DataGridView.OnMouseMove(MouseEventArgs e)   at System.Windows.Forms.Control.WmMouseMove(Message

**Comment by Hofknecht** [comment]
Thank you Peter S. for sending logfile.

here the complete callstack:

ERROR Application Crashed
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'e.ColumnIndex')
   at System.Windows.Forms.DataGridView.OnCellMouseMove(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.UpdateMouseEnteredCell(HitTestInfo hti, MouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
INFO Restart by 'ByThreadException'

Occured in version 1.0.17.42, previous version was 1.0.17.41, the new version was started for the 3rd time.
This leads to the assumption that it could be due to this https://github.com/Hofknecht/SystemTrayMenu/commit/4fefc4f2534ab562b804fc2a0dc2a600407ebba5#diff-6337fa50c6627adf9f095b0806158de71f0d7cf995a82f7147ad879223ede03a
There i changed that submenu will also close directly when moving mouse pointer to another folder and not only when the new submenu has been loaded.We already do this for files. There is a case when new folder needs a bit to load and the old one stayed open meanwhile.

Peter S.:
It happened once, after changing to new version
I think it was when I placed the mouse pointer on a folder I created,
after the menu was already open. But I'm not so sure, because the bug did not occured again.

**Comment by Hofknecht** [comment]
Thank you Ralf K. for answer.

This means my assumption from above is probably incorrect, it has probably to do with changes to 1.0.17.32


Ralf K.:
1.0.17.24 was the last version running very well. Since 1.0.17.32, 36, 40, 41, ... and above it doesn’t start without the bug. The bug runs right in the beginnung every time I start the tool.

**Comment by Hofknecht** [comment]
i can now reproduce

it is directly related to #172, see explanation here
https://github.com/Hofknecht/SystemTrayMenu/issues/172#issuecomment-850786485

so it was  Revision: a005582 [Feature] Show link overlay for files like lnk & URL (#166), version 1.0.17.26

Solution is to also cache icon for standardbrowser, which makes the stm also faster (<1ms each icon for call (URL) instead 3-5ms)
