### ISSUE TITLE
[BUG] Pipeline fails at NuGet restore 

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#187]
not related to code changes 

Last build working, 30.5.2021 at 22:14
https://dev.azure.com/MarkusHofknecht/SystemTrayMenu/_build/results?buildId=264&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=53352b99-bc56-513f-dcdf-57009ff4318b

```
C:\hostedtoolcache\windows\NuGet\5.9.1\x64\nuget.exe restore D:\a\1\s\SystemTrayMenu.sln -Verbosity Detailed -NonInteractive
NuGet Version: 5.9.1.11
MSBuild auto-detection: using msbuild version '16.9.0.16703' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\msbuild.exe "C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\jyzgvzll.ksq.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\nfzfty4c.ayi.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="C:\hostedtoolcache\windows\NuGet\5.9.1\x64\nuget.exe" /p:RestoreSolutionDirectory="D:\a\1\s\\" /p:SolutionDir="D:\a\1\s\\" /p:SolutionName="SystemTrayMenu"

Running restore 
```

![image](https://user-images.githubusercontent.com/52528841/120929520-a30ab680-c6e9-11eb-90f7-3944c26d948b.png)

Since 1.6.2021 not more working

https://dev.azure.com/MarkusHofknecht/SystemTrayMenu/_build/results?buildId=265&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=53352b99-bc56-513f-dcdf-57009ff4318b
```

C:\hostedtoolcache\windows\NuGet\5.9.1\x64\nuget.exe restore D:\a\1\s\SystemTrayMenu.sln -Verbosity Detailed -NonInteractive
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets(16,3): error MSB4019: The imported project "C:\hostedtoolcache\windows\dotnet\sdk\3.1.102\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.NuGet.targets" was not found. Confirm that the expression in the Import declaration "C:\hostedtoolcache\windows\dotnet\sdk\3.1.102\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.NuGet.targets" is correct, and that the file exists on disk. [D:\a\1\s\Packaging\Packaging.wapproj]

NuGet Version: 5.9.1.11
MSBuild auto-detection: using msbuild version '16.10.0.26302' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\msbuild.exe "C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\eytaua1n.coz.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\0wkeytmh.o1r.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="C:\hostedtoolcache\windows\NuGet\5.9.1\x64\nuget.exe" /p:RestoreSolutionDirectory="D:\a\1\s\\" /p:SolutionDir="D:\a\1\s\\" /p:SolutionName="SystemTrayMenu"
NuGet.CommandLine.ExitCodeException: Exception of type 'NuGet.CommandLine.ExitCodeException' was thrown.
   at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__63.MoveNext()
##[error]The nuget command failed with exit code(1) and error(C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets(16,3): error MSB4019: The imported project "C:\hostedtoolcache\windows\dotnet\sdk\3.1.102\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.NuGet.targets" was not found. Confirm that the expression in the Import declaration "C:\hostedtoolcache\windows\dotnet\sdk\3.1.102\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.NuGet.targets" is correct, and that the file exists on disk. [D:\a\1\s\Packaging\Packaging.wapproj])
##[error]Packages failed to restore


```

What we tried to solve the problem:

-run the pipeline again, as it solved the last time => still fails, no change

-check NuGet Version 5.9.1.11 in both the same, probably not a NuGet Version issue

-add tasks NuGet Tool Installer / NuGetToolInstaller@1 and NuGet Restore / NuGetCommand@2 again to assure-pipelines.yml  => still fails, no change

-Try to do it via msBuild: https://dev.azure.com/MarkusHofknecht/SystemTrayMenu/_build/results?buildId=286&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=71c7159a-2554-5189-e11d-21665ca4648a
=> wrong way, still fails, no change

**Comment by Hofknecht** [comment]
reverted the changes of the try with bb89755

find here out azure-pipelines.yml:
https://github.com/Hofknecht/SystemTrayMenu/blob/master/azure-pipelines.yml

**Comment by Hofknecht** [comment]
found the solution here
https://docs.microsoft.com/en-us/azure/devops/pipelines/packages/nuget-restore?view=azure-devops 

after changing to 
Restore NuGet packages with the .NET Core CLI task


```
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'
```

it was working
