### ISSUE TITLE
[BUG] Fix ArgumentException DirectoryNotFoundException introduced with 1.0.18.3

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#198]
a couple of bugs related to https://github.com/Hofknecht/SystemTrayMenu/issues/192
so intrdocued with 1.0.18.3

System.ArgumentException: The path is empty. (Parameter 'path') at System.IO.Path.GetFullPath(String path) at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options) at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized) at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options) at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options) at System.IO.Directory.GetFiles(String path) at SystemTrayMenu.Config.IsPathOK(String path) in D:\a\1\s\Config\Config.cs:line 119 at SystemTrayMenu.Config.LoadOrSetByUser() in D:\a\1\s\Config\Config.cs:line 62 at SystemTrayMenu.Program.Main(String[] args) in D:\a\1\s\Business\Program.cs:line 27

System.ArgumentException: The path is empty. (Parameter 'path') at System.IO.Path.GetFullPath(String path) at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options) at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized) at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options) at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options) at System.IO.Directory.GetFiles(String path) at SystemTrayMenu.Config.SetFolderByUser(Boolean save) in D:\a\1\s\Config\Config.cs:line 89 at SystemTrayMenu.Config.LoadOrSetByUser() in D:\a\1\s\Config\Config.cs:line 73 at SystemTrayMenu.Program.Main(String[] args) in D:\a\1\s\Business\Program.cs:line 27

System.IO.DirectoryNotFoundException: Could not find a part of the path
'B:\Portable\Launcher\SystemTrayMenu\Re Re JJR Start'. at
System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String
path, Boolean ignoreNotFound) at
System.IO.Enumeration.FileSystemEnumerator`1.Init() at
System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory,
Boolean isNormalized, EnumerationOptions options) at
System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory,
FindTransform transform, EnumerationOptions options, Boolean
isNormalized) at
System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String
directory, String expression, EnumerationOptions options) at
System.IO.Directory.InternalEnumeratePaths(String path, String
searchPattern, SearchTarget searchTarget, EnumerationOptions options) at
System.IO.Directory.GetFiles(String path) at
SystemTrayMenu.Config.SetFolderByUser(Boolean save) in
D:\a\1\s\Config\Config.cs:line 89 at
SystemTrayMenu.Config.LoadOrSetByUser() in
D:\a\1\s\Config\Config.cs:line 73 at
SystemTrayMenu.Program.Main(String[] args) in
D:\a\1\s\Business\Program.cs:line 27

**Comment by Hofknecht** [comment]
fixes also probably

SystemTrayMenu Bug reported 1.0.17.68
System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Shell32.Shell'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{286E6F1B-7113-4355-9562-96B7E9D64C54}' failed due to the following error: Schnittstelle nicht unterstützt (0x80004002 (E_NOINTERFACE)). at SystemTrayMenu.Utilities.FileLnk.GetShortcutFileNamePath(Object shortcutFilename) in D:\a\1\s\Utilities\File\FileLnk.cs:line 99 at SystemTrayMenu.Utilities.FileLnk.GetResolvedFileName(String shortcutFilename) in D:\a\1\s\Utilities\File\FileLnk.cs:line 21 at SystemTrayMenu.DataClasses.RowData.SetLnk(Boolean 

SystemTrayMenu Bug reported 1.0.17.67
System.IO.FileNotFoundException: File name: 'System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'   at TAFactory.IconPack.IconExtractor.LoadLibrary(String fileName)   at TAFactory.IconPack.IconHelper.ExtractAllIcons(String fileName)   at SystemTrayMenu.DataClasses.RowData.SetSln()   at SystemTrayMenu.DataClasses.RowData.ReadIcon(Boolean isDirectory, String

SystemTrayMenu Bug reported 1.0.17.63
System.IO.FileLoadException: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird. (0x80070020) at Shell32.FolderItem.get_GetLink() at SystemTrayMenu.Utilities.FileLnk.GetShortcutFileNamePath(Object shortcutFilename) in D:\a\1\s\Utilities\File\FileLnk.cs:line 106 at SystemTrayMenu.Utilities.FileLnk.GetResolvedFileName(String shortcutFilename) in D:\a\1\s\Utilities\File\FileLnk.cs:line 21 at SystemTrayMenu.DataClasses.RowData.SetLnk(Boolean
