### ISSUE TITLE
[BUG] drag, scroll and search at same time

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#335]
here is still a rare bug ArgumentOutOfRangeException

https://user-images.githubusercontent.com/52528841/154135932-d1cb5c41-afd8-4347-b6fc-8a6433654986.mp4

   at System.Windows.Forms.DataGridView.SetSelectedRowCore(Int32 rowIndex, Boolean selected)
   at System.Windows.Forms.DataGridView.SelectRowRange(Int32 rowIndexFrom, Int32 rowIndexTo, Boolean select)
   at System.Windows.Forms.DataGridView.OnRowSelectMouseMove(HitTestInfo hti)
   at System.Windows.Forms.DataGridView.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by Hofknecht** [comment]
solution is to disable search in this case
as when you drag drop a item (without swipe scroll, all items fit into main menu)
