### ISSUE TITLE
[BUG] Win32Exception (8): Not enough memory resources are available

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#468]
U serlinger reported:
System.ComponentModel.Win32Exception (8): Not enough memory resources are available to process this command.   at System.Drawing.Icon.Initialize(Int32 width, Int32 height)

Jon R. reported:
System.ComponentModel.Win32Exception (8): Not enough memory resources are available to process this command.   at System.Drawing.Icon.Initialize(Int32 width, Int32 height)

&

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception (8): Not enough memory resources are available to process this command.   at System.Drawing.Icon.Initialize(Int32 width, Int32 height)   at System.Drawing.Icon..ctor(Stream stream, Int32 width, Int32 height)   at System.Drawing.Icon..ctor(Stream stream)   --- End of inner exception stack trace ---   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1

**Comment by Hofknecht** [comment]
we asked both

> Hello,
> 
> Thank you for the feedback!
> 
> we created a issue here:
> 
> https://github.com/Hofknecht/SystemTrayMenu/issues/468
> 
> I don't think we can fix this directly, I tagged it once with 'help wanted'.
> Did that happen again? How much ram does your pc have? How long was the STM running and what were you doing before it happened? Are there any number of items involved or a specific behavior? We can't reproduce this yet.
> 
> Regards
> 
> Markus

**Comment by Hofknecht** [comment]
we got directly a answer, see here

```
Markus,

Honestly, I don’t remember any of the things I was doing before and after the STM acted up.  It happens now and again but I don’t think since the time I reported it in December.  The computer hardware info is in the snip below.

STM is really handy and cuts down a bunch of time that it takes navigating through File Explorer.  I use it extensively.
```

: )

ok good to hear that this error is rare
ram was ~ 16gb

needs further analyze

**Comment by Userlinger** [comment]
Hi, i have 32 gigs of ram. It occurred when checked the "recursive" box on a huge folder (17gig over 100.000 files). I could reproduce it back then (i tried twice). The error never occurred on everyday usage. 

btw thanks for creating STM. I had a similar thing in mind for myself and you saved me from trying to build it :)

**Comment by Hofknecht** [comment]
was reported once more from Jonny F. in v1.3.3:

System.ComponentModel.Win32Exception (8): Zur Verarbeitung dieses
Befehls sind nicht genügend Speicherressourcen verfügbar. at
System.Drawing.Icon.Initialize(Int32 width, Int32 height) at
InvokeStub_Icon..ctor(Object, Object, IntPtr*) at
System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args,
BindingFlags invokeAttr)

**Comment by Hofknecht** [comment]
SystemTrayMenu Bug reported 1.3.5.0
System.ComponentModel.Win32Exception (8): Not enough memory resources are available to process this command.   at System.Drawing.Icon.Initialize(Int32 width, Int32 height)   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

Sent from Mail for Windows
