### ISSUE TITLE
Unable to start SystemTrayMenu with multiple users (e.g. terminalserver)

### ISSUE THREAD

**Issue by BetaWayOfLife** [Hofknecht/SystemTrayMenu#526]
SystemTrayMenu only starts with the first user on the machine / server:

2024.06.21 07:27:17.082 1  ERROR Run as single instance failed
System.ComponentModel.Win32Exception (5): Zugriff verweigert
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at SystemTrayMenu.Utilities.SingleAppInstance.Initialize() in D:\a\1\s\Utilities\SingleAppInstance.cs:line 74

**Comment by Hofknecht** [comment]
@BetaWayOfLife 
related
#252
#511

currently we are not planning to change it so we will close this issue for now, maybe something for the future
